apiVersion: v1
kind: ServiceAccount
metadata:
  name: ad-platform-sa
  namespace: ad-platform
  labels:
    app.kubernetes.io/name: ad-platform
  annotations:
    # IRSA: binds this SA to an IAM role via OIDC federation
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ad-platform-irsa-role
